-- The PostgreSQL seed, schema (SPEC §testing.it). The MySQL shapes carry over
-- (utf8 text, BIGINT past 2^53, NUMERIC precision, JSONB, microsecond timestamps,
-- composite PK with FK, PK-less duplicate rows, a 60-column wide table, 1,000 bulk
-- rows, a view) plus what only postgres has: an enum type, schemas app and audit with
-- a cross-schema foreign key, text[], uuid, and a partial index.

CREATE TYPE user_status AS ENUM ('active', 'idle', 'banned');

CREATE TABLE users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT NOT NULL,
    email     TEXT NULL,
    status    user_status NOT NULL DEFAULT 'active',
    balance   NUMERIC(20,4) NOT NULL,
    flags     JSONB NULL,
    avatar    BYTEA NULL,
    big       BIGINT NOT NULL,
    born_at   TIMESTAMPTZ NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE orders (
    user_id BIGINT NOT NULL REFERENCES users (id),
    seq     INT NOT NULL,
    note    TEXT NULL,
    amount  NUMERIC(12,2) NOT NULL,
    placed  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, seq)
);

-- No primary key on purpose: paging must survive byte-identical duplicate rows.
CREATE TABLE events (
    at     TIMESTAMPTZ NOT NULL,
    kind   TEXT NOT NULL,
    detail JSONB NULL
);

CREATE TABLE wide (
    c01 TEXT NULL,
    c02 INT NULL,
    c03 NUMERIC(10,2) NULL,
    c04 TEXT NULL,
    c05 INT NULL,
    c06 NUMERIC(10,2) NULL,
    c07 TEXT NULL,
    c08 INT NULL,
    c09 NUMERIC(10,2) NULL,
    c10 TEXT NULL,
    c11 INT NULL,
    c12 NUMERIC(10,2) NULL,
    c13 TEXT NULL,
    c14 INT NULL,
    c15 NUMERIC(10,2) NULL,
    c16 TEXT NULL,
    c17 INT NULL,
    c18 NUMERIC(10,2) NULL,
    c19 TEXT NULL,
    c20 INT NULL,
    c21 NUMERIC(10,2) NULL,
    c22 TEXT NULL,
    c23 INT NULL,
    c24 NUMERIC(10,2) NULL,
    c25 TEXT NULL,
    c26 INT NULL,
    c27 NUMERIC(10,2) NULL,
    c28 TEXT NULL,
    c29 INT NULL,
    c30 NUMERIC(10,2) NULL,
    c31 TEXT NULL,
    c32 INT NULL,
    c33 NUMERIC(10,2) NULL,
    c34 TEXT NULL,
    c35 INT NULL,
    c36 NUMERIC(10,2) NULL,
    c37 TEXT NULL,
    c38 INT NULL,
    c39 NUMERIC(10,2) NULL,
    c40 TEXT NULL,
    c41 INT NULL,
    c42 NUMERIC(10,2) NULL,
    c43 TEXT NULL,
    c44 INT NULL,
    c45 NUMERIC(10,2) NULL,
    c46 TEXT NULL,
    c47 INT NULL,
    c48 NUMERIC(10,2) NULL,
    c49 TEXT NULL,
    c50 INT NULL,
    c51 NUMERIC(10,2) NULL,
    c52 TEXT NULL,
    c53 INT NULL,
    c54 NUMERIC(10,2) NULL,
    c55 TEXT NULL,
    c56 INT NULL,
    c57 NUMERIC(10,2) NULL,
    c58 TEXT NULL,
    c59 INT NULL,
    c60 NUMERIC(10,2) NULL
);

CREATE TABLE big_rows (
    n     INT PRIMARY KEY,
    label TEXT NOT NULL,
    qty   INT NOT NULL,
    price NUMERIC(12,2) NOT NULL
);

CREATE SCHEMA app;
CREATE SCHEMA audit;

CREATE TABLE app.documents (
    id         UUID PRIMARY KEY,
    title      TEXT NOT NULL,
    tags       TEXT[] NOT NULL DEFAULT '{}',
    created_by BIGINT NOT NULL REFERENCES public.users (id)
);

CREATE TABLE audit.log_entries (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc  UUID NOT NULL REFERENCES app.documents (id),
    at   TIMESTAMPTZ NOT NULL,
    note TEXT NULL
);

-- Partial on purpose: the browser's index list must show predicates, not pretend.
CREATE INDEX log_entries_noted_at ON audit.log_entries (at) WHERE note IS NOT NULL;

CREATE VIEW active_users AS
SELECT id, name, email, balance FROM users WHERE status = 'active';
